### ISSUE TITLE
Minor nits: Spelling of taken

### ISSUE THREAD

**Issue by secworks** [sebastien-riou/prince-c-ref#1]
A saw a minor spelling issue repeated two times in your prince c reference.
On the following lines the word "taken" is spelled as "takken"

https://github.com/sebastien-riou/prince-c-ref/blob/698f1f9785ba20ee29c8cd90b11695902547ef04/include/prince_ref.h#L80

https://github.com/sebastien-riou/prince-c-ref/blob/698f1f9785ba20ee29c8cd90b11695902547ef04/include/prince_ref.h#L93

**Comment by sebastien-riou** [comment]
Thanks for the review :-)
