### ISSUE TITLE
Incorrect results when built with clang++

### ISSUE THREAD

**Issue by sohnryang** [sebastien-riou/prince-c-ref#2]
# How to reproduce
```shell
$ $CXX=clang++ ./build_test.sh
$ ./prince-c-ref # the test fails
```

# `clang++` version
```shell
$ clang++ --version
clang version 11.1.0
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

The cipher runs fine when compiled under `-O1`. Anything higher than that causes the test to fail.

**Comment by sebastien-riou** [comment]
thanks for reporting, reproduced [here](https://wandbox.org/permlink/rY24pqoVMFxkRxhl)

**Comment by sebastien-riou** [comment]
narrow it down [here](https://wandbox.org/permlink/2Q5rvxQi8rqSZMIv). 

In prince_shift_rows:
````

shift_rows_out=0
	BBBBBBBB_BBBBBBBB in
	B000B000_B000B000 row
shift=64
shift_rows_out=ffffffffffffffff
````

Seems like I need digging into what C standard says about shift operations

**Comment by sebastien-riou** [comment]
shall be fixed now, please confirm.

**Comment by sohnryang** [comment]
Yes, it runs fine! :+1:
